"""Constantes da aplicação RegulaPRO."""

# Status de processos
STATUS_EM_ANALISE = "Em Análise"
STATUS_DEFERIDO = "Deferido"
STATUS_INDEFERIDO = "Indeferido"
STATUS_EM_ANDAMENTO = "Em Andamento"
STATUS_CONCLUIDO = "Concluído"
STATUS_ATRASADO = "Atrasado"
STATUS_AGUARDANDO = "Aguardando Documentos"
STATUS_CANCELADO = "Cancelado"

TODOS_STATUS = [
    STATUS_EM_ANDAMENTO,
    STATUS_EM_ANALISE,
    STATUS_AGUARDANDO,
    STATUS_DEFERIDO,
    STATUS_CONCLUIDO,
    STATUS_ATRASADO,
    STATUS_INDEFERIDO,
    STATUS_CANCELADO,
]

STATUS_ATIVOS = [STATUS_EM_ANDAMENTO, STATUS_EM_ANALISE, STATUS_AGUARDANDO]
STATUS_FINALIZADOS = [STATUS_DEFERIDO, STATUS_CONCLUIDO, STATUS_INDEFERIDO, STATUS_CANCELADO]

# Tipos de processo ANVISA
TIPO_REGISTRO = "Registro de Produto"
TIPO_RENOVACAO = "Renovação de Registro"
TIPO_LICENCA = "Licença de Funcionamento"
TIPO_AUTORIZACAO = "Autorização Especial"
TIPO_NOTIFICACAO = "Notificação"
TIPO_CERTIFICACAO = "Certificação"
TIPO_PETICAO = "Petição"
TIPO_RECURSO = "Recurso"

TIPOS_PROCESSO = [
    TIPO_REGISTRO,
    TIPO_RENOVACAO,
    TIPO_LICENCA,
    TIPO_AUTORIZACAO,
    TIPO_NOTIFICACAO,
    TIPO_CERTIFICACAO,
    TIPO_PETICAO,
    TIPO_RECURSO,
]

# Categorias de produto ANVISA
CATEGORIA_MEDICAMENTO = "Medicamento"
CATEGORIA_COSMETICO = "Cosmético"
CATEGORIA_SANEANTE = "Saneante"
CATEGORIA_ALIMENTO = "Alimento"
CATEGORIA_DISPOSITIVO = "Dispositivo Médico"
CATEGORIA_DIAGNOSTICO = "Produto para Diagnóstico"

CATEGORIAS_PRODUTO = [
    CATEGORIA_MEDICAMENTO,
    CATEGORIA_COSMETICO,
    CATEGORIA_SANEANTE,
    CATEGORIA_ALIMENTO,
    CATEGORIA_DISPOSITIVO,
    CATEGORIA_DIAGNOSTICO,
]

# Prioridades
PRIORIDADE_ALTA = "Alta"
PRIORIDADE_MEDIA = "Média"
PRIORIDADE_BAIXA = "Baixa"

PRIORIDADES = [PRIORIDADE_ALTA, PRIORIDADE_MEDIA, PRIORIDADE_BAIXA]

# Prazos padrão (em dias)
PRAZO_REGISTRO = 365
PRAZO_RENOVACAO = 180
PRAZO_LICENCA = 90
PRAZO_AUTORIZACAO = 60
PRAZO_NOTIFICACAO = 30

# Cores para gráficos
CORES_STATUS = {
    STATUS_EM_ANDAMENTO: "#3b82f6",
    STATUS_EM_ANALISE: "#f59e0b",
    STATUS_AGUARDANDO: "#8b5cf6",
    STATUS_DEFERIDO: "#10b981",
    STATUS_CONCLUIDO: "#00d084",
    STATUS_ATRASADO: "#ef4444",
    STATUS_INDEFERIDO: "#f97316",
    STATUS_CANCELADO: "#6b7280",
}
